version: '2'
services:
  bibliotheek-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: codesandwires/bibliotheek-backend
    ports:
      - "9001:8080"
      - "9002:9990"
    networks:
      - biblioheek-net
    container_name: bibliotheek-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bibliotheek-postgres:5432/bookdb
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: bibliotheek-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    networks:
      - biblioheek-net
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db123
      - POSTGRES_DB=bookdb
    restart: unless-stopped

networks:
  biblioheek-net:
    driver: "bridge"

volumes:
  postgres-data: